In [13]:
import numpy as np

## 🔬 NumPy para cálculos manipulación de datos numéricos 🚀

Imagina que estás trabajando en un proyecto de investigación científica en el campo de la física.
Necesitas realizar cálculos complejos y manipulación de datos numéricos a gran escala.
Aquí es donde entra en juego NumPy, una biblioteca esencial para la computación numérica en Python.

En tu proyecto, necesitas almacenar y manipular datos en arreglos multidimensionales.
Con NumPy, puedes crear fácilmente arreglos y realizar operaciones matemáticas optimizadas.

In [14]:
# Por ejemplo, creemos un arreglo unidimensional para representar mediciones de temperatura en diferentes días:
temperaturas = np.array([22.5, 24.7, 26.1, 23.8, 21.9])

# También podemos crear un arreglo bidimensional para representar mediciones de velocidad en diferentes puntos:
velocidades = np.array([[2.5, 3.1], [4.2, 3.8], [2.9, 2.7]])


In [15]:
# Ahora, imagina que necesitas calcular la media de las temperaturas y la velocidad máxima en cada punto.
# NumPy ofrece funciones estadísticas y matemáticas para facilitar estos cálculos:

media_temperaturas = np.mean(temperaturas)
velocidad_maxima = np.max(velocidades)

print("La temperatura media es:", media_temperaturas)
print("La velocidad máxima es:", velocidad_maxima)


La temperatura media es: 23.8
La velocidad máxima es: 4.2


In [16]:

# Además de realizar cálculos, también puedes acceder a elementos específicos en los arreglos.
# Por ejemplo, si deseas obtener la velocidad en el primer dato:

veloc_pr = velocidades[0, 1]
print("La segunda velocidad en el primer punto es:", veloc_pr)

La segunda velocidad en el primer punto es: 3.1


In [17]:
# NumPy también te permite generar arreglos con valores predefinidos.
# Por ejemplo, si necesitas crear una matriz de ceros de tamaño 2x3:

matriz_zeros = np.zeros((2, 3))
print("Matriz de ceros:")
print(matriz_zeros)


Matriz de ceros:
[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
# O si deseas crear una matriz de unos de tamaño 3x4:

matriz_unos = np.ones((3, 4))
print("Matriz de unos:")
print(matriz_unos)


Matriz de unos:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
# Además de eso, puedes generar arreglos con valores aleatorios utilizando NumPy.
# Por ejemplo, si necesitas generar una matriz 3x2 de números aleatorios:

matriz_aleatoria = np.random.rand(3, 2)
print("Matriz aleatoria:")
print(matriz_aleatoria)


Matriz aleatoria:
[[0.98540686 0.56898368]
 [0.58995346 0.63665198]
 [0.12044803 0.87660413]]


In [20]:

# NumPy también ofrece una amplia gama de funciones matemáticas y estadísticas.
# Por ejemplo, puedes calcular la desviación estándar de las temperaturas:

desviacion_estandar = np.std(temperaturas)
print("La desviación estándar de las temperaturas es:", desviacion_estandar)


La desviación estándar de las temperaturas es: 1.5099668870541507


In [21]:

# Además, puedes realizar operaciones vectorizadas en arreglos para un rendimiento más eficiente.
# Por ejemplo, si deseas calcular el cuadrado de cada elemento en el arreglo de velocidades:

velocidades_cuadrado = velocidades ** 2
print("Arreglo de velocidades al cuadrado:")
print(velocidades_cuadrado)


Arreglo de velocidades al cuadrado:
[[ 6.25  9.61]
 [17.64 14.44]
 [ 8.41  7.29]]


In [22]:

# NumPy también facilita la indexación y el filtrado de datos en arreglos.
# Por ejemplo, si deseas obtener las temperaturas mayores a 23 grados:

temperaturas_mayores_23 = temperaturas[temperaturas > 23]
print("Temperaturas mayores a 23 grados:")
print(temperaturas_mayores_23)


Temperaturas mayores a 23 grados:
[24.7 26.1 23.8]



En resumen, NumPy es una herramienta esencial para la computación numérica en Python.
Proporciona arreglos multidimensionales eficientes, funciones matemáticas y estadísticas,
operaciones vectorizadas, indexación avanzada y mucho más. Es ampliamente utilizado en
campos como la ciencia de datos, el aprendizaje automático, la física y la ingeniería.